"""Add iso639 column to language

Revision ID: 1182b2eaa96e
Revises: da6b4f4980ed
Create Date: 2025-04-26 13:10:27.544519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1182b2eaa96e'
down_revision: Union[str, None] = 'da6b4f4980ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language', sa.Column('iso639_1', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('language', 'iso639_1')
    # ### end Alembic commands ###
