"""Add title column to expertise model

Revision ID: 207ea439e1b5
Revises: 61532826f6b3
Create Date: 2025-05-01 12:58:44.091336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '207ea439e1b5'
down_revision: Union[str, None] = '61532826f6b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expertise_translation', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expertise_translation', 'title')
    # ### end Alembic commands ###
