"""Add transation for institution

Revision ID: 2cb800f5f72c
Revises: 66ed8f64b574
Create Date: 2025-04-26 12:58:39.563442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cb800f5f72c'
down_revision: Union[str, None] = '66ed8f64b574'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institution_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('institution', sa.Column('city', sa.String(), nullable=True))
    op.drop_column('institution', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institution', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('institution', 'city')
    op.drop_table('institution_translation')
    # ### end Alembic commands ###
