"""Add address table and establish relationship to institution

Revision ID: 42b197b973f8
Revises: 1182b2eaa96e
Create Date: 2025-04-26 13:15:51.351548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42b197b973f8'
down_revision: Union[str, None] = '1182b2eaa96e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('zip', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('institution', sa.Column('address_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'institution', 'institution', ['address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'institution', type_='foreignkey')
    op.drop_column('institution', 'address_id')
    op.drop_table('address')
    # ### end Alembic commands ###
