"""Add profile picture to personal details

Revision ID: 4cb54d061d41
Revises: e890faf0b2cc
Create Date: 2025-06-29 20:39:43.653057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cb54d061d41'
down_revision: Union[str, None] = 'e890faf0b2cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_details', sa.Column('profile_picture_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'personal_details', 'image', ['profile_picture_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'personal_details', type_='foreignkey')
    op.drop_column('personal_details', 'profile_picture_id')
    # ### end Alembic commands ###
