"""Remove city column from institution

Revision ID: 67da2640ca5b
Revises: 42b197b973f8
Create Date: 2025-04-26 13:17:22.133041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67da2640ca5b'
down_revision: Union[str, None] = '42b197b973f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('institution', 'city')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institution', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
