"""Add sort column for expertises

Revision ID: b4bb6d2d5dc2
Revises: 4cb54d061d41
Create Date: 2025-06-30 14:16:00.119220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4bb6d2d5dc2'
down_revision: Union[str, None] = '4cb54d061d41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expertise', sa.Column('sort', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expertise', 'sort')
    # ### end Alembic commands ###
