"""Add transation for institution

Revision ID: da6b4f4980ed
Revises: 2cb800f5f72c
Create Date: 2025-04-26 13:00:23.568952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da6b4f4980ed'
down_revision: Union[str, None] = '2cb800f5f72c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institution_translation', sa.Column('institution_id', sa.Integer(), nullable=True))
    op.add_column('institution_translation', sa.Column('language_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'institution_translation', 'institution', ['institution_id'], ['id'])
    op.create_foreign_key(None, 'institution_translation', 'language', ['language_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'institution_translation', type_='foreignkey')
    op.drop_constraint(None, 'institution_translation', type_='foreignkey')
    op.drop_column('institution_translation', 'language_id')
    op.drop_column('institution_translation', 'institution_id')
    # ### end Alembic commands ###
