"""Introduce image object

Revision ID: e890faf0b2cc
Revises: 6ddde6e1d0a4
Create Date: 2025-06-14 18:59:29.524305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e890faf0b2cc'
down_revision: Union[str, None] = '6ddde6e1d0a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('filepath', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    op.create_index(op.f('ix_image_id'), 'image', ['id'], unique=False)
    op.add_column('work', sa.Column('thumbnail_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'work', 'image', ['thumbnail_id'], ['id'])
    op.drop_column('work', 'thumbnail')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work', sa.Column('thumbnail', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'work', type_='foreignkey')
    op.drop_column('work', 'thumbnail_id')
    op.drop_index(op.f('ix_image_id'), table_name='image')
    op.drop_table('image')
    # ### end Alembic commands ###
