"""Fix typo in contact column name

Revision ID: f80165f605cc
Revises: 12010c1ea6c6
Create Date: 2025-12-13 12:56:19.902243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f80165f605cc'
down_revision: Union[str, None] = '12010c1ea6c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('send', sa.Boolean(), nullable=True))
    op.drop_column('contact', 'sended')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('sended', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('contact', 'send')
    # ### end Alembic commands ###
