"""Remove instition id from works

Revision ID: fe8e4a0eabe2
Revises: b39fda01de79
Create Date: 2025-05-01 13:32:52.713150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe8e4a0eabe2'
down_revision: Union[str, None] = 'b39fda01de79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('work_institution_id_fkey', 'work', type_='foreignkey')
    op.drop_column('work', 'institution_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work', sa.Column('institution_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('work_institution_id_fkey', 'work', 'institution', ['institution_id'], ['id'])
    # ### end Alembic commands ###
