name: Docker
values:
  - key: base-url
    value: 'http://localhost'
    enabled: true
  - key: user
    value: ''
    enabled: true
  - key: password
    value: ''
    enabled: true
  - key: user-non-admin
    value: ''
    enabled: true
  - key: password-non-admin
    value: ''
    enabled: true
color: 120
