name: Run Postman Tests

on: push

jobs:
  postman-test:
    runs-on: ubuntu-latest

    # All services that are needed for testing
    services:
      # Database for testing
      postgres:
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: ${{ secrets.DB_TEST_PWD }}
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    # The testing steps
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate Configuration
      run: |
        sed -i~ '/^DB_PASSWORD=/s/=.*/="${{ secrets.DB_TEST_PWD }}"/' .env.example
        sed -i~ 's/REPLACE_PASSWORD/${{ secrets.DB_TEST_PWD }}/' alembic.ini.example

        mv .env.example .env
        mv alembic.ini.example alembic.ini
        cat alembic.ini.example


    - name: Start FastAPI App
      run: |
        nohup fastapi run app/main.py --port 8000 &
        sleep 10

    - name: Initialize Database
      env:
        PGPASSWORD: ${{ secrets.DB_TEST_PWD }}
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql-client

        # Apply database migrations
        alembic upgrade head

        # Execute SQL file to seed test users
        PGPASSWORD=${PGPASSWORD} psql -h localhost -U postgres -d postgres -f ./scripts/create_test_users.sql

    - name: Install Postman CLI
      run: |
        curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

    - name: Login to Postman CLI
      run: |
        postman login --with-api-key ${{ secrets.POSTMAN_TOKEN }}

    - name: Run Postman Tests
      run: |
        # Run Postman tests
        postman collection run 9159996-20961b0d-bf53-445d-ad18-4f6f31d69009 -e 9159996-bdc3bc36-e5f3-47f2-ab24-336e8c72e582
